/**
 * The committed icon PNGs, checked for the property that keeps flipping.
 *
 * `public/icons/*.png` are generated by `npm run icons`, which needs macOS's
 * `qlmanage` and `sips` — so CI cannot regenerate and diff them the way the
 * `data` job does for the codes JSON. That leaves them the one generated
 * artefact with no freshness gate, and the gap is not theoretical: the corners
 * silently went fully opaque **twice**, once when the rounding was dropped from
 * the SVGs and once when a failure after the render left half-built files in
 * place. On a dark toolbar that renders as a solid square.
 *
 * This does not need the toolchain. It reads the committed bytes and asserts
 * the one thing that matters, so it runs in the ordinary `test` job.
 */
import { readFileSync } from 'node:fs';
import { inflateSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const SIZES = [16, 32, 48, 128] as const;

function iconBytes(size: number): Buffer {
  return readFileSync(fileURLToPath(new URL(`../public/icons/icon${size}.png`, import.meta.url)));
}

/** IHDR width/height/bit-depth/colour-type, straight out of the header. */
function header(png: Buffer): { width: number; height: number; depth: number; colour: number } {
  expect(png.subarray(0, 8)).toEqual(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
  return {
    width: png.readUInt32BE(16),
    height: png.readUInt32BE(20),
    depth: png[24]!,
    colour: png[25]!,
  };
}

/**
 * The top-left pixel's alpha.
 *
 * Only the first scanline is needed, so this decompresses IDAT and reads byte
 * 4 — filter byte, then R, G, B, A. Every filter type leaves the first pixel's
 * bytes equal to the raw value on the first row, because the predictors all
 * reference pixels that are off the edge and therefore zero.
 */
function topLeftAlpha(png: Buffer): number {
  let pos = 8;
  const parts: Buffer[] = [];
  while (pos + 8 <= png.length) {
    const length = png.readUInt32BE(pos);
    const kind = png.subarray(pos + 4, pos + 8).toString('ascii');
    if (kind === 'IDAT') parts.push(png.subarray(pos + 8, pos + 8 + length));
    pos += 12 + length;
    if (kind === 'IEND') break;
  }
  const raw = inflateSync(Buffer.concat(parts));
  return raw[4]!;
}

describe('the committed extension icons', () => {
  for (const size of SIZES) {
    describe(`icon${size}.png`, () => {
      it('is a square RGBA PNG of the right size', () => {
        const { width, height, depth, colour } = header(iconBytes(size));
        expect({ width, height }).toEqual({ width: size, height: size });
        // Colour type 6 is RGBA. Without an alpha channel there is nowhere for
        // the rounded corners to live at all.
        expect({ depth, colour }).toEqual({ depth: 8, colour: 6 });
      });

      it('has a transparent corner', () => {
        // The regression, twice over: qlmanage flattens onto an opaque ground,
        // so a tile that has not been through `round-icon-corners.py` has
        // alpha 255 here and renders as a square.
        expect(topLeftAlpha(iconBytes(size))).toBe(0);
      });
    });
  }
});
